server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: sregtsop
  name: mini_go_backend
  sslmode: disable

redis:
  address: localhost:6379
  password: ""
  db: 0
